"use strict";
var paintvec_1 = require("paintvec");
var Color_1 = require("../lib/Color");
var Context_1 = require("../lib/Context");
var Pixmap_1 = require("../lib/Pixmap");
var Shape_1 = require("../lib/Shape");
var Fill_1 = require("../lib/Fill");
var Model_1 = require("../lib/Model");
var DrawTarget_1 = require("../lib/DrawTarget");
var context = new Context_1.Context(document.getElementById("canvas"));
var pixmap = new Pixmap_1.Pixmap(context, { size: new paintvec_1.Vec2(400, 400) });
var drawTarget = new DrawTarget_1.PixmapDrawTarget(context, pixmap);
drawTarget.clear(new Color_1.Color(0.9, 0.9, 0.9, 1));
var shape = new Shape_1.RectShape(context);
shape.rect = new paintvec_1.Rect(new paintvec_1.Vec2(100, 100), new paintvec_1.Vec2(200, 300));
var fill = new Fill_1.ColorFill(context);
fill.color = new Color_1.Color(0.9, 0.1, 0.2, 1);
var model = new Model_1.Model(context, shape, fill);
drawTarget.draw(model);
drawTarget.transform = paintvec_1.Transform.rotate(0.1 * Math.PI);
drawTarget.blendMode = "dst-out";
drawTarget.draw(model);
var canvasDrawTarget = new DrawTarget_1.CanvasDrawTarget(context);
var pixmapShape = new Shape_1.RectShape(context);
pixmapShape.rect = new paintvec_1.Rect(new paintvec_1.Vec2(0), pixmap.size);
var pixmapFill = new Fill_1.PixmapFill(context);
pixmapFill.pixmap = pixmap;
var pixmapModel = new Model_1.Model(context, pixmapShape, pixmapFill);
canvasDrawTarget.draw(pixmapModel);
