"use strict";
const paintvec_1 = require("paintvec");
const lib_1 = require("../lib");
const context = new lib_1.Context(document.getElementById("canvas"));
const pixmap = new lib_1.Pixmap(context, { size: new paintvec_1.Vec2(400, 400) });
const drawTarget = new lib_1.PixmapDrawTarget(context, pixmap);
drawTarget.clear(new lib_1.Color(0.9, 0.9, 0.9, 1));
const shape = new lib_1.RectShape(context);
shape.rect = new paintvec_1.Rect(new paintvec_1.Vec2(100, 100), new paintvec_1.Vec2(200, 300));
const fill = new lib_1.ColorFill(context);
fill.color = new lib_1.Color(0.9, 0.1, 0.2, 1);
const model = new lib_1.Model(context, shape, fill);
drawTarget.draw(model);
drawTarget.transform = paintvec_1.Transform.rotate(0.1 * Math.PI);
drawTarget.blendMode = "dst-out";
drawTarget.draw(model);
const canvasDrawTarget = new lib_1.CanvasDrawTarget(context);
const pixmapShape = new lib_1.RectShape(context);
pixmapShape.rect = new paintvec_1.Rect(new paintvec_1.Vec2(0), pixmap.size);
const pixmapFill = new lib_1.PixmapFill(context);
pixmapFill.pixmap = pixmap;
const pixmapModel = new lib_1.Model(context, pixmapShape, pixmapFill);
canvasDrawTarget.draw(pixmapModel);
