"use strict";
var paintvec_1 = require("paintvec");
var Color_1 = require("../src/Color");
var Context_1 = require("../src/Context");
var Pixmap_1 = require("../src/Pixmap");
var Shape_1 = require("../src/Shape");
var Fill_1 = require("../src/Fill");
var Model_1 = require("../src/Model");
var DrawTarget_1 = require("../src/DrawTarget");
var context = new Context_1.Context(document.getElementById("canvas"));
var pixmap = new Pixmap_1.Pixmap(context, new paintvec_1.Vec2(100, 100));
var drawTarget = new DrawTarget_1.PixmapDrawTarget(context, pixmap);
var shape = new Shape_1.RectShape(context);
shape.rect = new paintvec_1.Rect(new paintvec_1.Vec2(40, 40), new paintvec_1.Vec2(80, 80));
var fill = new Fill_1.ColorFill(context);
fill.color = new Color_1.Color(0.5, 0.4, 0.3, 1);
var model = new Model_1.Model(context, shape, fill);
drawTarget.draw(model);
drawTarget.transform = paintvec_1.Transform.scale(new paintvec_1.Vec2(0.5));
drawTarget.blendMode = "dst-out";
drawTarget.draw(model);
